"""Tablas de incidencias y asistencia individual

Revision ID: 29dbbc785d74
Revises: aed4b2104d19
Create Date: 2026-04-18 13:19:37.235219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dbbc785d74'
down_revision = 'aed4b2104d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencia_estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencia')
    op.drop_table('asistencia_estudiante')
    # ### end Alembic commands ###
