"""Agregada tabla AsistenciaPersonal

Revision ID: ee0197785179
Revises: 
Create Date: 2026-04-11 18:01:58.339756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0197785179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencia_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('matricula_base', sa.Integer(), nullable=False),
    sa.Column('asistentes', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencia_personal')
    # ### end Alembic commands ###
