"""Agregando tablas Estudiante y Representante

Revision ID: aed4b2104d19
Revises: ee0197785179
Create Date: 2026-04-18 12:38:13.818206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed4b2104d19'
down_revision = 'ee0197785179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('parentesco', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula_escolar', sa.String(length=30), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('lugar_nacimiento', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('num_acta', sa.String(length=50), nullable=True),
    sa.Column('num_oficio', sa.String(length=50), nullable=True),
    sa.Column('talla', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('calzado', sa.String(length=10), nullable=True),
    sa.Column('tipaje', sa.String(length=10), nullable=True),
    sa.Column('vacunacion_completa', sa.String(length=20), nullable=True),
    sa.Column('alergias', sa.String(length=200), nullable=True),
    sa.Column('neurodivergencia', sa.Boolean(), nullable=True),
    sa.Column('neuro_detalle', sa.String(length=200), nullable=True),
    sa.Column('nuevo_ingreso', sa.Boolean(), nullable=True),
    sa.Column('institucion_procedencia', sa.String(length=150), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.Column('representante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.ForeignKeyConstraint(['representante_id'], ['representante.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_escolar')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudiante')
    op.drop_table('representante')
    # ### end Alembic commands ###
